# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendLocalTensor = channel.unary_unary(
                '/federated.Federation/sendLocalTensor',
                request_serializer=federated__pb2.ClientTensorRequest.SerializeToString,
                response_deserializer=federated__pb2.ServerReceivedResponse.FromString,
                _registered_method=True)
        self.sendAggregatedTensor = channel.unary_unary(
                '/federated.Federation/sendAggregatedTensor',
                request_serializer=federated__pb2.Empty.SerializeToString,
                response_deserializer=federated__pb2.ServerAggregatedTensorRequest.FromString,
                _registered_method=True)


class FederationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendLocalTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendAggregatedTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendLocalTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.sendLocalTensor,
                    request_deserializer=federated__pb2.ClientTensorRequest.FromString,
                    response_serializer=federated__pb2.ServerReceivedResponse.SerializeToString,
            ),
            'sendAggregatedTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.sendAggregatedTensor,
                    request_deserializer=federated__pb2.Empty.FromString,
                    response_serializer=federated__pb2.ServerAggregatedTensorRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.Federation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.Federation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Federation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendLocalTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.Federation/sendLocalTensor',
            federated__pb2.ClientTensorRequest.SerializeToString,
            federated__pb2.ServerReceivedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendAggregatedTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.Federation/sendAggregatedTensor',
            federated__pb2.Empty.SerializeToString,
            federated__pb2.ServerAggregatedTensorRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
